# Generated by Django 2.2.14 on 2022-05-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='app_goods.Goods', verbose_name='goods'),
        ),
    ]
