# Generated by Django 2.2.14 on 2022-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100, verbose_name='goods name')),
                ('description', models.TextField(verbose_name='description')),
                ('categoryidx', models.IntegerField()),
                ('image', models.ImageField(upload_to='goods/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsInShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsidx', models.IntegerField()),
                ('shopidx', models.IntegerField()),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'goods in shop',
                'verbose_name_plural': 'goods in shops',
            },
        ),
        migrations.CreateModel(
            name='GoodsStorages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsidx', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('limited', models.BooleanField(default=False, verbose_name='limited edition')),
            ],
            options={
                'verbose_name': 'goods storage',
                'verbose_name_plural': 'goods storages',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsidx', models.IntegerField()),
                ('startofferdate', models.DateTimeField(verbose_name='date offer start')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50, verbose_name='shop name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='shops/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
    ]
