# Generated by Django 3.2 on 2022-05-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100, verbose_name='goods name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='goods/', verbose_name='image')),
                ('categoryidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_categories.subcategories', verbose_name='category')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50, verbose_name='shop name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='shops/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startofferdate', models.DateTimeField(verbose_name='date offer start')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='app_goods.goods', verbose_name='goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsStorages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('limited', models.BooleanField(default=False, verbose_name='limited edition')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='app_goods.goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'goods storage',
                'verbose_name_plural': 'goods storages',
            },
        ),
        migrations.CreateModel(
            name='GoodsInShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goods', verbose_name='goods')),
                ('shopidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.shops', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'goods in shop',
                'verbose_name_plural': 'goods in shops',
            },
        ),
    ]
