# Generated by Django 2.2.14 on 2022-05-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_categories.Subcategories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='goodsinshops',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Goods', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='goodsinshops',
            name='shopidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Shops', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='goodsstorages',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='app_goods.Goods', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='app_goods.Goods', verbose_name='goods'),
        ),
    ]
