# Generated by Django 2.2.14 on 2022-04-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app_goods', '0002_auto_20220424_1306'), ('app_goods', '0003_auto_20220424_1542'), ('app_goods', '0004_auto_20220424_1550'), ('app_goods', '0005_auto_20220424_1656'), ('app_goods', '0006_auto_20220424_1659')]

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorages',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='app_goods.Goods', verbose_name='goods'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startofferdate', models.DateTimeField(verbose_name='date offer start')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Goods', verbose_name='goods')),
            ],
        ),
    ]
