# Generated by Django 2.2.14 on 2022-05-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_auto_20220424_1306_squashed_0006_auto_20220424_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_categories.Subcategories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='app_goods.Goods', verbose_name='goods'),
        ),
    ]
