# Generated by Django 2.2.14 on 2022-04-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristictype', models.CharField(max_length=25, verbose_name='characteristic type')),
            ],
            options={
                'verbose_name': 'characteristic type',
                'verbose_name_plural': 'characteristic types',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=50, verbose_name='subcategory name')),
                ('goodscharacteristics', models.TextField(verbose_name='list of characteristics')),
                ('categoryidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categories.Categories', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5, verbose_name='characteristic value')),
                ('characteristictype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categories.CharacteristicTypes', verbose_name='characteristic type')),
            ],
            options={
                'verbose_name': 'characteristic',
                'verbose_name_plural': 'characteristics',
            },
        ),
    ]
