# Generated by Django 3.2 on 2022-06-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0001_initial'),
        ('app_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goods', verbose_name='goods'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_categories.categories', verbose_name='parent'),
        ),
    ]
