# Generated by Django 2.2.14 on 2022-04-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='discount rule name')),
                ('discountvalue', models.FloatField(verbose_name='discount value')),
                ('goodsset', models.TextField(verbose_name='goods list for discount')),
            ],
            options={
                'verbose_name': 'discount rule',
                'verbose_name_plural': 'discount_rules',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='discount type')),
            ],
            options={
                'verbose_name': 'discount type',
                'verbose_name_plural': 'discount types',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(verbose_name='card number')),
                ('foreignaccount', models.IntegerField(verbose_name='foreign account')),
            ],
            options={
                'verbose_name': 'payment rule',
                'verbose_name_plural': 'payment methods',
            },
        ),
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.IntegerField(verbose_name='normal shipping method ')),
                ('express', models.IntegerField(verbose_name='express shipping method')),
            ],
            options={
                'verbose_name': 'shipment method',
                'verbose_name_plural': 'shipment methods',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freenormal', models.FloatField(verbose_name='free shipping ')),
                ('paidnormal', models.FloatField(verbose_name='standard shipping ')),
                ('paidexpress', models.FloatField(verbose_name='express shipping ')),
            ],
            options={
                'verbose_name': 'shipment rule',
                'verbose_name_plural': 'shipment rules',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(verbose_name='order list')),
                ('orderdate', models.DateTimeField(auto_now=True, verbose_name='order date')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='order total price')),
                ('address', models.CharField(max_length=50, verbose_name='order delivery address')),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.PaymentMethod', verbose_name='payment method')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.ShipmentMethod', verbose_name='shipment method')),
                ('useridx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='discount description')),
                ('startdate', models.DateField(verbose_name='discount start date')),
                ('enddate', models.DateField(verbose_name='discount end date')),
                ('isactive', models.BooleanField(default=False, verbose_name='discount activity')),
                ('priority', models.IntegerField(default=0, verbose_name='discount priority')),
                ('discountruleidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.DiscountRule')),
                ('discounttypeidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.DiscountType')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
            },
        ),
    ]
