# Generated by Django 3.2 on 2022-06-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
        ('app_categories', '0002_initial'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setnumber', models.IntegerField(choices=[(1, 'First set'), (2, 'Second set')], verbose_name='set number')),
                ('categoriesidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='app_categories.categories', verbose_name='categories')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='discount name')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='discount priority')),
                ('description', models.TextField(default='', verbose_name='discount description')),
                ('active', models.BooleanField(default=False, verbose_name='discount is active')),
                ('type', models.IntegerField(choices=[(1, 'Good discount'), (2, 'Set discount'), (3, 'Discount on the number/total value of items in the cart')], verbose_name='discount type')),
                ('startdate', models.DateTimeField(verbose_name='discount start date')),
                ('stopdate', models.DateTimeField(verbose_name='discount stop date')),
                ('discountpercentage', models.PositiveSmallIntegerField(default=0, verbose_name='discount value in percent')),
                ('discountamount', models.PositiveSmallIntegerField(default=0, verbose_name='fixed amount of discount')),
                ('fixedcost', models.PositiveSmallIntegerField(default=0, verbose_name='fixed cost')),
                ('minimumvalue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimum value of items in the cart')),
                ('numberofitems', models.IntegerField(default=0, verbose_name='number of items in the cart')),
            ],
            options={
                'verbose_name': 'discounts list',
                'verbose_name_plural': 'discounts list',
            },
        ),
        migrations.CreateModel(
            name='GoodsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setnumber', models.IntegerField(choices=[(1, 'First set'), (2, 'Second set')], verbose_name='set number')),
                ('discountsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.discounts', verbose_name='discounts')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='app_goods.goods', verbose_name='goods')),
            ],
        ),
        migrations.DeleteModel(
            name='ShipmentMethod',
        ),
        migrations.DeleteModel(
            name='ShipmentRules',
        ),
        migrations.AddField(
            model_name='categoriesset',
            name='discountsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.discounts', verbose_name='discounts'),
        ),
    ]
