# Generated by Django 2.2.14 on 2022-04-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderdate',
            new_name='dt',
        ),
    ]
