# Generated by Django 2.2.14 on 2022-04-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
        ('app_orders', '0002_auto_20220408_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentdiscount', models.IntegerField(default=0, verbose_name='percent discount')),
                ('normaldiscount', models.IntegerField(default=1, verbose_name='normal_discount')),
                ('fixedprice', models.IntegerField(default=2, verbose_name='fixed_price')),
            ],
            options={
                'verbose_name': 'discount rule',
                'verbose_name_plural': 'discounts_rules',
            },
        ),
        migrations.CreateModel(
            name='GoodsDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsdiscount', models.FloatField(verbose_name='goods discount')),
                ('discountruleidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.DiscountsRules', verbose_name='discount rule')),
                ('goodsidx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'goods discount',
                'verbose_name_plural': 'goods discounts',
            },
        ),
        migrations.CreateModel(
            name='GoodsDiscountsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdt', models.DateTimeField(verbose_name='start date')),
                ('enddt', models.DateTimeField(verbose_name='end date')),
                ('isactive', models.BooleanField(verbose_name='is active')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'goods discount calendar',
                'verbose_name_plural': 'goods discounts calendar',
            },
        ),
        migrations.CreateModel(
            name='GoodsSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsset', models.TextField(verbose_name='goods set')),
                ('setdiscount', models.FloatField(verbose_name='set discount')),
                ('discountruleidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.DiscountsRules', verbose_name='discount rule')),
                ('goodsidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.Goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'goods set',
                'verbose_name_plural': 'goods sets',
            },
        ),
        migrations.CreateModel(
            name='SetsDiscountsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdt', models.DateTimeField(verbose_name='start date')),
                ('enddt', models.DateTimeField(verbose_name='end date')),
                ('isactive', models.BooleanField(verbose_name='active')),
                ('setidx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.GoodsSets', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'set discount calendar',
                'verbose_name_plural': 'sets discounts calendar',
            },
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='DiscountRule',
        ),
        migrations.DeleteModel(
            name='DiscountType',
        ),
    ]
