# Generated by Django 2.2.14 on 2022-05-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_auto_20220415_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountsrules',
            options={'verbose_name': 'discount rule', 'verbose_name_plural': 'discounts rules'},
        ),
        migrations.AlterField(
            model_name='discountsrules',
            name='fixedprice',
            field=models.IntegerField(default=2, verbose_name='fixed price'),
        ),
        migrations.AlterField(
            model_name='discountsrules',
            name='normaldiscount',
            field=models.IntegerField(default=1, verbose_name='normal discount'),
        ),
        migrations.AlterField(
            model_name='goodsdiscounts',
            name='goodsidx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='app_goods.Goods', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='goodssets',
            name='goodsidx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='app_goods.Goods', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card',
            field=models.IntegerField(default=0, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='foreignaccount',
            field=models.IntegerField(default=1, verbose_name='foreign account'),
        ),
        migrations.AlterField(
            model_name='shipmentmethod',
            name='express',
            field=models.IntegerField(default=1, verbose_name='express shipping method'),
        ),
        migrations.AlterField(
            model_name='shipmentmethod',
            name='normal',
            field=models.IntegerField(default=0, verbose_name='normal shipping method '),
        ),
        migrations.AlterField(
            model_name='shipmentrules',
            name='freenormal',
            field=models.FloatField(default=2000, verbose_name='free shipping'),
        ),
        migrations.AlterField(
            model_name='shipmentrules',
            name='paidexpress',
            field=models.FloatField(default=500, verbose_name='express shipping'),
        ),
        migrations.AlterField(
            model_name='shipmentrules',
            name='paidnormal',
            field=models.FloatField(default=200, verbose_name='standard shipping'),
        ),
    ]
